spec-version: 0.36.0

name: traq

# The package version.
# See the Haskell package versioning policy (PVP) for standards
# guiding when and how versions should be incremented.
# https://pvp.haskell.org
# PVP summary:     
#        +-+------- breaking API changes
#        | | +----- non-breaking API additions
#        | | | +--- code changes with no API change
version: 0.2.0.0

author: Anurudh Peduri <anurudhp97@gmail.com>
maintainer: Anurudh Peduri <anurudhp97@gmail.com>
synopsis: Traq - Estimating Quantum Cost of Classical Programs
description:
  The `Traq` framework to perform quantum cost analysis of classical programs.
  Supports input-dependent cost analysis of a probabilistic source language,
  and compilation to a classical-quantum target language.
category: Math

extra-doc-files:
  - Readme.md

ghc-options:
  - -Wall
  - -fprint-typechecker-elaboration

dependencies:
  - base >= 4.10 && < 5
  - containers >= 0.6 && < 1
  - extra >= 1.8 && < 2
  - transformers >= 0.5
  - mtl >= 2.2.2
  - microlens-ghc ^>= 0.4 
  - microlens-mtl ^>= 0.2
  - lens ^>= 5.3
  - parsec ^>= 3.1.17
  - algebra ^>= 4.3

default-extensions:
  - LambdaCase
  - NamedFieldPuns
  - ScopedTypeVariables
  - ApplicativeDo
  - RankNTypes
  - FlexibleContexts
  - TypeFamilies
  - TypeOperators
  - MultiWayIf
  - EmptyCase

library:
  source-dirs: src
  # default-extensions:
  #   - Safe

_exe_opts: &exe_opts
  source-dirs: tools
  dependencies:
    - traq
    - optparse-applicative ^>= 0.18
    - random
    - random-shuffle
    - timeit ^>= 2.0
  default-extensions:
    - RecordWildCards

_expt_opts: &expt_opts
  source-dirs: experiments
  dependencies:
    - traq
    - optparse-applicative ^>= 0.18
    - random
    - random-shuffle
    - timeit ^>= 2.0
  default-extensions:
    - RecordWildCards

executables:
  ### Tools
  uqplcompile:
    main: uqplcompile.hs
    <<: *exe_opts
  cqplcompile:
    main: cqplcompile.hs
    <<: *exe_opts
  ### Experiments & Examples
  matrixsearch:
    main: matrixsearch.hs
    <<: *expt_opts
  matrixsearchqcost:
    main: matrixsearchqcost.hs
    <<: *expt_opts
  matrixsearchdemo:
    main: demo.hs
    <<: *expt_opts
    source-dirs: examples/matrix_search
  knapsackdemo:
    main: demo.hs
    <<: *expt_opts
    source-dirs: examples/tree_generator
  timing:
    main: timing.hs
    <<: *expt_opts
  compile_loc:
    main: compile_loc.hs
    <<: *expt_opts


tests:
  spec:
      main: Spec.hs
      source-dirs:
        - test
      dependencies:
        - traq
        - hspec >= 2.11.0
        - QuickCheck
        - HUnit-approx
      cpp-options: -DTEST
      build-tools: hspec-discover
